---
  - name: Update apt cache if needed
    apt: "update_cache=yes cache_valid_time=14400"
  - name: install prerequisites
    apt:
     name:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common
       - docker-compose
  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repo
    apt_repository: 
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: install docker
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io 
      update_cache: yes
  - name: add user permissions
    shell: "usermod -aG docker $USER"